% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  letterpaper,
  DIV=11,
  numbers=noendperiod]{scrartcl}

\usepackage{amsmath,amssymb}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else  
    % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
% Make \paragraph and \subparagraph free-standing
\makeatletter
\ifx\paragraph\undefined\else
  \let\oldparagraph\paragraph
  \renewcommand{\paragraph}{
    \@ifstar
      \xxxParagraphStar
      \xxxParagraphNoStar
  }
  \newcommand{\xxxParagraphStar}[1]{\oldparagraph*{#1}\mbox{}}
  \newcommand{\xxxParagraphNoStar}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
  \let\oldsubparagraph\subparagraph
  \renewcommand{\subparagraph}{
    \@ifstar
      \xxxSubParagraphStar
      \xxxSubParagraphNoStar
  }
  \newcommand{\xxxSubParagraphStar}[1]{\oldsubparagraph*{#1}\mbox{}}
  \newcommand{\xxxSubParagraphNoStar}[1]{\oldsubparagraph{#1}\mbox{}}
\fi
\makeatother


\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}

\KOMAoption{captions}{tableheading}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\usepackage{bookmark}

\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same} % disable monospaced font for URLs
\hypersetup{
  pdftitle={Development of a value-based scoring system for the WAItE using the OPUF in a sample of adults},
  pdfauthor={Will King; Tomos Robinson; Angela Bate; Laura Ternent},
  pdfkeywords={template, demo},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}


\title{Development of a value-based scoring system for the WAItE using
the OPUF in a sample of adults}
\author{Will King \and Tomos Robinson \and Angela Bate \and Laura
Ternent}
\date{}

\begin{document}
\maketitle
\begin{abstract}
Ipsum nostra facilisis sapien nullam. Facilisi himenaeos pharetra
ultricies scelerisque non fusce quisque aliquam netus tellus. Dictum
tellus et sociis quisque ornare ad a natoque magna blandit. Tortor duis
aptent cursus lacus inceptos tristique magnis dictumst. Taciti varius
nascetur aliquet hac ornare vitae ultricies. Rhoncus primis purus morbi
aliquet quam cubilia nullam malesuada ridiculus.
\end{abstract}


\section{Introduction}\label{sec-introduction}

This chapter presents the introduction, methods, results and discussion
from an empirical study developing a utility value set for the WAItE
using online personal utility functions (OPUF) with a representative
sample of UK adults.

\subsection{Compositional preference elicitation
methods}\label{compositional-preference-elicitation-methods}

Preference elicitation methods generally speaking, fall into two
categories: compositional and decompositional (Keeney and Raiffa 1979;
Marsh et al. 2016; Belton and Stewart 2002). That is, methods like DCE,
BWS and TTO elicit preference orderings from individuals for an entire
health state (composed of a combination of domains and levels) and then
responses are decomposed to identify marginal contributions of each
domain and level in each health state. Models like multinomial logit,
mixed logit and latent class are frequently used to decompose responses
to decompositional preference elicitation tasks (Hauber et al. 2016).
Coefficients estimated in these models form the basis of dis/utility
values for each domain and level in a descriptive system.

Conversely, compositional methods seek to identify preferences for each
domain weighting and level rating individually for the number of domains
and levels in a given descriptive system. Therefore, statistical models
to elicit coefficients for each individual domain and level are not
required and responses to each domain weighting and level rating are
combined (in addition to an anchoring factor) to yield dis/utility
values for each domain and level in the descriptive system.
Compositional approaches can take many forms from simple VAS scores to
using semantic categories and ranking methods (Bana E Costa and Vansnick
1999; Danner et al. 2011; Oliveira et al. 2018). These approaches have
been used successfully in multi-criteria decision analysis (MCDA), but
have been used less extensively in the preference elicitation space.
Since the development of the OPUF, compositional approaches to elicit
preferences have become more commonplace and a number of countries are
using the OPUF to elicit value sets specific to their population
(Brodszky et al. 2023).

\subsection{From PUF to OPUF}\label{from-puf-to-opuf}

Personal utility functions were first used in the context of preference
elicitation by Devlin et al.~(2019) (Devlin et al. 2019) to estimate the
feasibility for using this approach to estimate a value set for the
EQ5D-5L. Since the feasibility for the underlying PUF methods were
established, the approach has been expanded by Schneider and colleagues
and converted into an online personal utility functions (OPUF) survey
built initially using RShiny (P. P. Schneider et al. 2022) and
subsequently using Javascript (available
\href{https://eq5d5l.me}{here}). Since the development of the OPUF, a
number of descriptive systems and different research teams have begun
utilising this method to elicit value sets (Bray, Tudor Edwards, and
Schneider 2024; Brodszky et al. 2023).

\subsection{An overview of the OPUF
structure}\label{an-overview-of-the-opuf-structure}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Domain weighting: This section is composed of two parts. First, domain
  ranking is completed where participants identify their most important
  domain. Second, respondents complete the domain weighting (swing
  weighting) where the relative importance of other domains is
  ascertained using their most important domain as a reference point.
  These questions are presented in Figure \ref{fig:domain weighting}.
\item
  Level ratings: This element of the OPUF has varied across different
  iterations of the survey. Schnieder et al.~(2022) (P. P. Schneider et
  al. 2022) asked participants to rank the levels within the descriptive
  system generally (i.e.~for any given domain), while other iterations
  have administered separate level rating questions for each domain in
  the descriptive system (Bray, Tudor Edwards, and Schneider 2024).
  Selection of method requires a trade-off between participant burden
  and sensitivity of level ratings to each domain. Figure
  \ref{fig:level rating} presents the level rating question for the
  pain/discomfort domain of the EQ5D-5L.
\item
  Anchoring factor: A task is required to rescale the latent
  coefficients estimated via combining level ratings and domain weights
  onto the QALY scale. Participants are presented with a binary choice
  between the PITS state (or another state) of a given descriptive
  system and ``being dead''. If the PITS state is chosen, participants
  are asked to rank the PITS state on a VAS from 1 (full health) to 0
  (dead). If ``being dead'' is chosen, participants are asked to rank
  ``being dead'' on a VAS from 1 (full health) to 0 (PITS state).
  Responses to these respective questions provide the anchoring factor.
  Anchoring questions, such that PITS is preferred to dead, are
  presented in Figure \ref{fig:anchoring factor}.
\end{enumerate}

\subsection{OPUF logic and mathematics}\label{sec-OPUF_methods}

This section presents the logic and underlying mathematics required to
convert the raw OPUF responses from one person into an anchored value
set for the WAItE descriptive system. This example assumes that level
ratings are obtained for each domain separately, therefore mathematics
presented here differs to those presented elsewhere (P. P. Schneider et
al. 2022). Example response data are used for demonstration in this
section and are presented in Table \ref{tab:example_raw_OPUF}.

\subsubsection{Example responses}\label{example-responses}

\begin{table}[ht]
\centering
\caption{Example individual responses to the OPUF}

\footnotesize
\begin{tabular}{p{2cm} p{0.6cm} p{0.9cm} p{0.6cm} p{1.8cm} p{2cm} p{1.6cm} p{2.8cm}}
\toprule
& Tired & Walking & Sports & Concentration & Embarrassment & Unhappiness & Treated Differently \\
\midrule
Never          & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
Almost Never   & 14 & 26 & 21 & 15 & 16 & 12 & 19 \\
Sometimes      & 57 & 55 & 63 & 54 & 38 & 26 & 66 \\
Often          & 83 & 82 & 85 & 86 & 64 & 38 & 91 \\
Always         & 100 & 100 & 100 & 100 & 100 & 100 & 100 \\
\midrule
Domain Weighting & 28 & 33 & 36 & 45 & 100 & 34 & 56 \\
Normalised Weighting & 0.084 & 0.099 & 0.108 & 0.136 & 0.301 & 0.102 & 0.169 \\
\midrule
\multicolumn{8}{l}{WAItE PITS better than dead = Yes} \\
\multicolumn{8}{l}{Anchoring Task Response = 20} \\
\multicolumn{8}{l}{PITS Utility Value = 0.2} \\
\bottomrule
\end{tabular}
\end{table}

Level ratings (presented in Table \ref{tab:example_raw_OPUF}) are
converted to coefficients bounded between 0-1 (shown in Equation
\ref{eq:level_rescale}). Level rating coefficients are presented in
Matrix \ref{level_matrix}. Attribute weights (presented in Table
\ref{tab:example_raw_OPUF}) are then normalised to sum to the value of 1
by dividing each weight by the sum of all weights (shown in Equation
\ref{eq:weight_normalise}). Normalised attribute weights are presented
in Vector \ref{weight_vector}.

\begin{equation}\label{eq:level_rescale}
    L_{ij} \cdot 0.01
\end{equation}

\begin{equation}\label{level_matrix}
L_{ij} = 
\begin{bmatrix}
0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0.14 & 0.26 & 0.21 & 0.15 & 0.16 & 0.12 & 0.19 \\
0.57 & 0.55 & 0.63 & 0.54 & 0.38 & 0.26 & 0.66 \\
0.83 & 0.82 & 0.85 & 0.86 & 0.64 & 0.38 & 0.91 \\
1 & 1 & 1 & 1 & 1 & 1 & 1 \\
\end{bmatrix}
\end{equation} \textbackslash{}
\begin{equation}\label{eq:weight_normalise}
    \frac{w_{j}}{\sum{w_j}}
\end{equation}

\begin{equation}\label{weight_vector}
w_j = \begin{bmatrix}
    0.08& 0.10& 0.11& 0.14& 0.30& 0.10& 0.17
\end{bmatrix} 
\end{equation} \textbackslash{} \%\%\%\%\%\%\%\%\%\%\% combining weights
and levels Combining the attribute weights (Vector \ref{weight_vector})
with the level coefficients (Matrix \ref{level_matrix}) via element-wise
multiplication (shown in Equation \ref{eq:element_wise_multiplication}
gives the coefficient matrix presented in Matrix \ref{coeff_matrix}.
Once the coefficient matrix has been estimated, preference values can be
estimated on the 0-1 QALY scale where the worst health state (PITS state
denoted 5555555) is zero and the best health state (denoted 1111111) is
one. These latent coefficients must now be rescaled to incorporate the
results from the PITS anchoring task so that the minimum utility value
possible is equal to the PITS value.

\begin{equation}\label{eq:element_wise_multiplication}
    L_{ij} \cdot  w_{j} = {\tilde{M}}_{ij}
\end{equation}

\begin{equation}\label{coeff_matrix}
\tilde{M}_{ij} =  
\begin{bmatrix}
0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0.01 & 0.03 & 0.02 & 0.02 & 0.05 & 0.01 & 0.03 \\
0.05 & 0.05 & 0.07 & 0.07 & 0.11 & 0.03 & 0.11 \\
0.07 & 0.08 & 0.09 & 0.12 & 0.19 & 0.04 & 0.15 \\
0.08 & 0.10 & 0.11 & 0.14 & 0.30 & 0.10 & 0.17
\end{bmatrix}
\end{equation} \textbackslash{} To rescale the latent coefficient matrix
to incorporate the anchoring task, the coefficient matrix is multiplied
by the compliment of the PITS value (shown in Equation
\ref{eq:anchoring}) to give the anchored coefficient matrix presented in
Matrix \ref{ma:anchored_matrix}.

\begin{equation}\label{eq:anchoring}
    \tilde{M}_{ij} \cdot (1-P) \quad \backepsilon \quad P = 0.2 
\end{equation}

\begin{equation}\label{ma:anchored_matrix}
\tilde{V}_{ij} =  
\begin{bmatrix}
0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0.01 & 0.02 & 0.02 & 0.02 & 0.04 & 0.01 & 0.02 \\
0.04 & 0.04 & 0.06 & 0.06 & 0.09 & 0.02 & 0.09 \\
0.06 & 0.06 & 0.07 & 0.10 & 0.15 & 0.03 & 0.12 \\
0.06 & 0.08 & 0.09 & 0.11 & 0.24 & 0.08 & 0.14 \\
\end{bmatrix}
\end{equation} \textbackslash{}

Once the attribute and level labels are reintroduced to the anchored
coefficient matrix this forms the value set which presents the
disutility corresponding to each attribute level combination presented
in the WAItE. Table \ref{example valueset} presents the WAItE example
PUF value set. Equations \ref{eq:HS1} present examples of how to
estimate a utility value given a specific WAItE health state.

\begin{table}[ht]
\centering
\caption{WAItE example PUF value set}

\footnotesize
\begin{tabular}{p{2cm} p{0.6cm} p{0.9cm} p{0.6cm} p{1.8cm} p{2cm} p{1.6cm} p{2.8cm}}
\toprule
& Tired & Walking & Sports & Concentration & Embarrassment & Unhappiness & Treated Differently \\
\midrule
Never          & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
Almost Never   & 0.01 & 0.02 & 0.02 & 0.02 & 0.04 & 0.01 & 0.02 \\
Sometimes      & 0.04 & 0.04 & 0.06 & 0.06 & 0.09 & 0.02 & 0.09 \\
Often          & 0.06 & 0.06 & 0.07 & 0.10 & 0.15 & 0.03 & 0.12 \\
Always         & 0.06 & 0.08 & 0.09 & 0.11 & 0.24 & 0.08 & 0.14 \\
\bottomrule
\multicolumn{8}{l}{*Coefficients anchored by a PITS utility value of 0.2}
\end{tabular}
\end{table}

\begin{equation}\label{eq:HS1}
\begin{aligned}
    
    \text{Health State [5555555]} &\Rightarrow 1 - (0.06 + 0.08 + 0.09 + 0.11 + 0.24 + 0.08 + 0.14) = 0.20 
    
    \text{Health State [5223445]} &\Rightarrow 1 - (0.06 + 0.02 + 0.02 + 0.06 + 0.15 + 0.03 + 0.14) = 0.52
\end{aligned}
\end{equation}

\%\begin{equation}\label{eq:HS2}
    %\text{Health State [2222222]} \Rightarrow 1 - (0.03 + 0.02 + 0.01 + 0.01 + 0.02 + 0.02 + 0.04) = 0.85
%\end{equation}

## Aggregation to social utility function
The OPUF is designed to be able to estimate personal utility functions and so estimation occurs on an individual basis. Aggregating personal utility functions to a social utility function (SUF) takes place by taking a mean of all the individual personal utility functions from your sample. This operation is presented in Equation \ref{eq:mean_valueset}. 

\begin{equation}\label{eq:mean_valueset}
\bar{V}_{{ij}} = \frac{\sum_{\tilde{V}_{{ij}}}^{}}{N}
\end{equation}

\section{Methods}\label{methods}

\subsection{Recruitment}\label{recruitment}

This study recruited (n=300) adults to respond to a quality-of-life
survey hosted online. Study participants were recruited based on
specific quotas to form a representative sample based on UK census data.
The survey was hosted on the
\hyperlink{https://www.prolific.com}{Prolific} platform which invited
paid respondents to complete the Weight-specific Adolescent Instrument
for Economic evaluation (WAItE) version of the Online Personal Utility
Functions (OPUF) survey. A demonstration of the OPUF survey and
questions is available
\hyperlink{https://survey.valorem.health/waite_opuf_adult2}{here}.
Informed consent was obtained at the outset of the survey and
participants reserved the right to withdraw at any point without giving
a reason. Participants who withdrew were not paid and their data
deleted. Participation in this survey was estimated to take
approximately fifteen minutes to complete and participants received
£2.50 as a payment upon completion. This is in line with reimbursements
rates from other OPUF studies (P. P. Schneider et al. 2022; Bray, Tudor
Edwards, and Schneider 2024) and is in line with recommended
reimbursement rates from Prolific
(\hyperlink{www.prolific.com}{www.prolific.com}). The survey was
designed to be an unassisted survey administered online (no face-to-face
contact) and no identifiable data was collected. Statistical analysis
was conducted on the survey data. Newcastle University Medical School
Ethics Committee approved this study (reference 49737/2023). The survey
structure is detailed in Section~\ref{sec-surveystructure}.

\subsection{Survey structure}\label{sec-surveystructure}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Consent and Prolific ID: Participants were asked to consent to
  participate and enter their unique Prolific ID. This enables
  demographic information held by Prolific on their participants to be
  linked to each respondent.
\item
  WAItE descriptive system: Participants were asked to complete the
  WAItE descriptive system (presented in Figure
  \ref{fig:waite_descriptive})to describe their current health state.
\item
  Dimension selection\}: Participants were presented with the worst
  level for each WAItE dimension and asked to choose which health
  problem would have the most negative impact on their quality of life.
  The dimension chosen is then used in the subsequent dimension swing
  weighting task.\\
\item
  Dimension swing weighting: Participants were presented with each
  dimension in the WAItE and asked to consider an improvement from the
  worst level of that dimension to the best level of that dimension.
  Participants were asked to rank this improvement on a visual slider
  from 0-100 where the most important dimension (chosen in the previous
  task) is fixed at 100. Participants were reminded to use their most
  important dimension as a reference point.\\
\item
  Level rating: Participants were presented with a specific dimension of
  the WAItE and shown each level within that dimension. Levels best and
  worst (never and always) were fixed at 0 and 100 respectively.
  Participants were asked to rank the intermediate levels within each
  dimension using the fixed levels as a reference point.
\item
  Anchoring: Participants were presented with a binary choice asking
  whether they prefer the worst state of the WAItE (PITS state) or
  death. If participants choose the worst state of the WAItE, a second
  question is asked which asks them to rank the WAITE PITS state on a
  visual analogue scale where zero is labelled as being dead and one
  hundred is labelled as no health problems. If participants choose
  death in the binary choice, they were asked to rank being dead on a
  visual analogue scale where zero is labelled as the WAItE PITS state
  and one hundred is labelled as no health problems.
\item
  Survey feedback and demographic questions: Participants were asked
  about how difficult they found the task to complete and demographic
  information on age, gender, ethnicity, education, employment and
  weight status.
\end{enumerate}

\subsection{Live survey}\label{live-survey}

\subsection{Missing data}\label{missing-data}

Through the survey design process the potential for large amounts of
missing data has been mitigated by ensuring responses were compulsory to
certain questions. However for ethical reasons, we allowed participants
to not answer the questions relating to death. For participants who do
not provide responses to the anchoring questions, their responses were
imputed using multiple imputation by chained equations (MICE) (White,
Royston, and Wood 2011) which were informed by demographic information
and dimension weighting responses.

\subsection{Preference heterogeneity}\label{preference-heterogeneity}

As personal utility function are estimated on an individual basis,
exploring preference heterogeneity between individuals in the sample is
straightforward. Investigating the heterogeneity of preferences between
individuals, requires a measure of dis/similarity to quantify how far
apart two PUFs are (P. Schneider et al. 2024). The measurement and
estimation of preference heterogeneity in this section will follow
methods detailed by Schneider et al.~(2024) (P. Schneider et al. 2024).
Each PUF estimated in this study was represented by a vector of 78,125
health state utility values for each respondent in the sample. In order
to assess the dis/similarity between these PUFs, we used the euclidean
difference measure (EUD). Analogous to a line between two points on a
two dimensional plane, the EUD between two PUFs denotes the shortest
path length in a 78,125 dimensional space. It is computed as the square
root of the sum of the squared differences between the PUFs of
individuals (i) and (j) (presented in Equation \ref{eq:EUD}). Once PUFs
have been estimated for all individuals in the sample, pairwise EUD was
estimated for all possible pairwise combinations within the sample.
Pairwise EUD was stored in an {[}N (\times) N{]} distance matrix.

\begin{equation} \label{eq:EUD}
  \begin{aligned}
    d_{EUD}(i,j) & =\sqrt{\sum_{}^{}(u_{i}(s_{1})-u_{j}(s_{1}))^{2}+ ... +(u_{i}(s_{78125})-u_{j}(s_{78125}))^{2}}\\
      & \backepsilon \quad \quad s = \{1111111, 2111111, ..., 5555555\}\\
  \end{aligned}
\end{equation}

\subsection{Permutational analysis of
variance}\label{permutational-analysis-of-variance}

Permutational analysis of variance (PERMANOVA), analogous to analysis of
variance, is a geometric partitioning of variation across a multivariate
data cloud, definied in the space of any given dissimilarity measure, in
response to one or more groups {[}Anderson (2017);
Anderson2013PERMANOVATesting{]}. This method of statistical testing has
been used most commonly in ecological research to test for population
dispersion among different subgroups (Souza et al. 2013). PERMANOVA
decomposes the total distances between observations (SS(\_T)) into
within-groups (SS(\_W)) and between groups sum-of-squares (SS(\_B)).
Equation \ref{eq:sumsquares} details the estimation of total and
within-groups sum-of-squares. Mathematical notation presented here is
reproduced from Schneider et al.~(2024) (P. Schneider et al. 2024) for
consistency.

\begin{equation} \label{eq:sumsquares}
    SS_{T} = \frac{1}{N}\sum_{i=1}^{N-1}\sum_{j=i+1}^{N}d(i,j)^{2}; \quad SS_{W} = \sum_{i=1}^{N-1}\sum_{j=i+1}^{N}d(i,j)^{2}\epsilon_{ij}^{\ell}/n_{\ell}
\end{equation}

where N is the total sample size (=300), (d(i,j)\^{}2) is the squared
distance between the PUFs of participants (i) and (j),
(\epsilon\emph{\{i,j\}) indicator which is 1, if participants (i) and
(j) belong to the same group, and 0 if they do not, and (n}\{\ell\}) is
the size for group (\ell). Then, SS(\_B) can then be calculated as
SS(\_B) = SS(T) -- SS(\_W), which allows calculating the pseudo F
statistic for (p) groups:

\begin{equation}
    F= \frac{(\frac{SS_B}{p-1})}{(\frac{SS_W}{N-p})}
\end{equation}

Further details about the mathematical and statistical properties of
PERMANOVA are available elsewhere {[}P. Schneider et al. (2024);
Anderson2017; Anderson2013PERMANOVATesting{]}. In this study, we used
PERMANOVA to explore the variability in WAItE health state preferences
(individual value sets) between various subgroups. A multivariate
PERMANOVA model was estimated with subgroups of: age, gender,
self-reported weight status, education, employment status and ethncity.

\subsection{Sensitivity analysis}\label{sensitivity-analysis}

In an experimental sensitivity analysis, preference heterogeneity was
assessed using EUD estimated based on individual's personal utility
functions anchored using the social PITS utility value (henceforth
referred to as EUD2). This differed to prior preference heterogeneity
estimation as individual variation in PITS utility values were not
included in the EUD2 estimation. EUD2 was entirely composed by
differences in level ratings and domain weights. Further details on the
derivation of EUD2 are presented in Appendix \ref{app:EUD_derivation}.

\section{Results}\label{results}

\subsection{Study participants}\label{study-participants}

A sample of 334 individuals were approached to participate in the study
via the survey company \hyperlink{https://www.prolific.com}{Prolific}.
Individuals that successfully inputted their unique Prolific ID and
obtained a correct completion code from the end of the study were
included in the analysis sample and received a small payment (£2.50) for
their participation. Seven participants were excluded from the study as
they had an incorrect completion code and did not enter the correct
unique Prolific ID. Therefore no data was available on those seven
participants and so they were excluded from the analysis. An additional
participant was excluded from the analysis due to completing the survey
in eighteen seconds (well under the prespecified minimum time limit of 2
minutes). Two respondents timed-out while completing the survey and were
therefore not included. Twenty-four individuals chose not complete the
study (referred to by Prolific as `returned' participants). This left an
analysis sample of N=300 participants who successfully completed the
survey. A representative sample based on UK census data was obtained
from Prolific. A summary of demographic information collected in the
OPUF are presented in Table \ref{tab:demographicdataadultOPUF}.

\subsection{Survey duration}\label{survey-duration}

The mean (SD) and median (IQR) survey completion time in minutes was
9.66 (5.85) and 8.15 (5.88; 11.89). Table~\ref{tbl-time} summarises how
much time was spent completing each individual section of the survey.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2941}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2059}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.3088}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.0882}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.1029}}@{}}

\caption{\label{tbl-time}Survey completion times (secs)}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Section
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Mean (SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Median (Q1; Q3)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Max
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
WAItE & 73 (90.1) & 53 (38; 77) & 10 & 1066 \\
Dimension ranking & 35.4 (50.6) & 26 (16; 40) & 2 & 741 \\
Dimension weighting & 115.7 (94.9) & 91.5 (69.8; 142.2) & 18 & 1380 \\
Level rating & 220.5 (206.4) & 171 (119; 249) & 34 & 2158 \\
PITS vs death & 25.5 (45.4) & 16.5 (11; 25.2) & 4 & 620 \\
PITS-VAS & 37.3 (39.2) & 29 (21; 45) & 5 & 605 \\
PITS-VAS & 37.3 (39.2) & 29 (21; 45) & 5 & 605 \\
Total (secs) & 579.5 (351.1) & 489.2 (352.5; 713.4) & 126.7 & 3738.2 \\
Total (mins) & 9.66 (5.85) & 8.15 (5.88; 11.89) & 2.11 & 62.3 \\

\end{longtable}

\subsection{WAItE descriptive system}\label{waite-descriptive-system}

Responses to the WAItE descriptive system are presented in Table
\ref{tab:demographicdataadultOPUF}. Feeling tired and avoiding doing
sport were the domains that were most frequently experienced by
participants in our analysis sample. WAItE summary statistics were in
line with results from previous studies (Robinson and Oluboyede 2019).

\begin{table}[h] 
\caption{Summary of demographic data collected in the OPUF}

\centering
\begingroup\small
\begin{tabular}{p{12cm} r{3cm}}
\toprule
\textbf{Participant characteristics (N=300)} & \textbf{N (\%)} \\
  \hline
\textbf{Age} &  \\
  \quad 18-24 & 32 (10.9\%) \\ 
  \quad 25-34 & 50 (17\%) \\ 
  \quad 35-44 & 48 (16.3\%) \\ 
  \quad 45-54 & 49 (16.7\%) \\ 
  \quad 55-64 & 81 (27.6\%) \\ 
  \quad 65-90 & 34 (11.6\%) \\
  \quad Not Stated & 6 (2.0\%) \\
  \textbf{Gender} & \\
  \quad Female & 154 (51\%) \\
  \quad Male & 144 (48\%) \\
  \quad Non-binary & 1 (0\%) \\
  \textbf{Ethnicity} & \\
  \quad White & 251 (84\%) \\
  \quad Asian & 23 (8\%) \\
  \quad Black & 11 (4\%) \\
  \quad Mixed & 10 (3\%) \\
  \quad Other & 5 (2\%) \\
  \textbf{Weight Status} & \\
  \quad Normal & 154 (51\%) \\
  \quad Overweight & 104 (35\%) \\
  \quad Obese & 30 (10\%) \\
  \quad Underweight & 8 (3\%) \\
  \quad Prefer not to say & 4 (1\%) \\
  \textbf{Education} & \\
  \quad Degree & 147 (49\%) \\
  \quad A Level & 64 (21\%) \\
  \quad Higher Education & 46 (15\%) \\
  \quad Other & 20 (7\%) \\
  \quad GCSE A-C & 18 (6\%) \\
  \quad GCSE D-G & 5 (2\%) \\
  \textbf{Occupation} & \\
  \quad Full-time & 130 (43\%) \\
  \quad Part-time & 62 (21\%) \\
  \quad Not Paid & 30 (10\%) \\
  \quad Other & 31 (10\%) \\
  \quad Student & 17 (6\%) \\
  \quad Unemployed & 18 (6\%) \\
  \quad Not Stated & 9 (3\%) \\
  \quad Starting a New Job & 3 (1\%) \\
   \textbf{WAItE} & Mean (SD) \\
   \quad Tiredness & 3.4 (0.8) \\
   \quad Walking & 2.1 (1.1) \\
   \quad Sport & 3.3 (1.3) \\
   \quad Concentration & 2.7 (1.0) \\
   \quad Embarrassment & 2.2 (1.2) \\
   \quad Unhappiness & 2.3 (1.0) \\
   \quad Treated differently & 1.9 (0.9) \\
   \quad \textbf{Total} & 17.8 (4.8) \\
   \bottomrule
\end{tabular}
\endgroup
\end{table}

\subsection{Level ratings}\label{level-ratings}

Level ratings are presented individually for each different domain in
Table~\ref{tbl-level}. The best and worst levels (\textit{Always} and
\textit{Never}) were fixed at 0 and 100 respectively. The second best
level (\textit{Almost never}) had the lowest VAS score in the Sports and
Embarrassment domain, while the second worst level (\textit{Often}) had
the highest VAS score in the Concentration domain. In this question,
higher VAS scores indicate worse states of health.

\begin{longtable}[]{@{}lllll@{}}

\caption{\label{tbl-level}Summary of OPUF level ratings by domain}

\tabularnewline

\toprule\noalign{}
Section & Mean (SD) & Median (Q1; Q3) & Min & Max \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Almost never & 20.323 (23.208) & 10 (5; 25) & 0 & 100 \\
Sometimes & 36.31 (19.185) & 33.5 (20; 50) & 0 & 100 \\
Often & 62.217 (23.934) & 70 (50; 80) & 0 & 100 \\
Almost never & 19.39 (21.839) & 10 (6; 21) & 0 & 100 \\
Sometimes & 37.677 (19.373) & 40 (24; 50) & 0 & 100 \\
Often & 62.967 (26.167) & 71 (50; 80) & 0 & 100 \\
Almost never & 16.63 (20.978) & 10 (5; 20) & 0 & 100 \\
Sometimes & 29.487 (22.015) & 25 (10; 45) & 0 & 100 \\
Often & 49.843 (29.624) & 50.5 (24.5; 75) & 0 & 100 \\
Almost never & 21.393 (22.1) & 14 (7; 25) & 0 & 100 \\
Sometimes & 41.56 (20.101) & 40 (25.8; 53.2) & 0 & 100 \\
Often & 64.503 (26.195) & 73 (50; 80.2) & 0 & 100 \\
Almost never & 16.59 (22.292) & 10 (4; 20) & 0 & 100 \\
Sometimes & 29.417 (21.615) & 25 (10; 50) & 0 & 100 \\
Often & 47.91 (30.445) & 50 (20; 75) & 0 & 100 \\
Almost never & 21.13 (22.235) & 13 (6; 25) & 0 & 100 \\
Sometimes & 41.363 (22.128) & 41.5 (25; 56) & 0 & 100 \\
Often & 63.557 (28.187) & 75 (50; 85) & 0 & 100 \\
Almost never & 20.93 (24.366) & 11 (5; 25) & 0 & 100 \\
Sometimes & 35.52 (22.774) & 34.5 (19.8; 50) & 0 & 100 \\
Often & 55.857 (30.552) & 60.5 (31; 80) & 0 & 100 \\

\end{longtable}

\subsection{Domain weights}\label{domain-weights}

Summary statistics of domain weightings are presented in
Table~\ref{tbl-domain}. On average, Tiredness (76.5) and Unhappiness
(70) were considered to be more important to participants than
Embarrassment (40.1) and Sports (42.3). There was less variability in
domain weighting responses to Tiredness than responses to Treated
differently or Embarrassment. \%TODO: Add relative attribute importance
section with normalised RAI score

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.3529}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2353}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2647}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.0882}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.0588}}@{}}

\caption{\label{tbl-domain}Summary of OPUF domain weights and anchoring
responses}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Section
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Mean (SD)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Median (Q1; Q3)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Max
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
Tired & 76.513 (28.358) & 90 (60; 100) & 1 & 100 \\
Walking & 65.53 (32.49) & 75 (40; 100) & 0 & 100 \\
Sports & 42.32 (32.81) & 35 (11; 70) & 0 & 100 \\
Concentration & 67.897 (30.949) & 80 (44; 99.2) & 0 & 100 \\
Embarrassment & 40.143 (34.344) & 30 (9; 70) & 0 & 100 \\
Unhappiness & 69.997 (31.946) & 80 (50; 100) & 0 & 100 \\
Treated differently & 52.093 (35.564) & 50 (15.8; 86) & 0 & 100 \\
PITS preferred to death & 0.879 (0.327) & 1 (1; 1) & 0 & 1 \\
PITS-VAS & 56.057 (31.287) & 54 (30; 85) & 0 & 100 \\
Dead-VAS & 42.528 (31.583) & 38.5 (13.2; 63.5) & 1 & 100 \\
PITS VAS uncensored & -0.025 (5.95) & 0.5 (0.2; 0.8) & -99 & 1 \\
PITS VAS censored & 0.431 (0.485) & 0.5 (0.2; 0.8) & -1 & 1 \\
PITS Utility Value & 0.282 (1.456) & 0.5 (0.2; 0.8) & -14.3 & 1 \\

\end{longtable}

\subsection{Anchoring}\label{anchoring}

The majority of respondents in the sample preferred the WAItE PITS state
to being dead (87\%). Therefore, 13\% of participants answered the
dead-VAS and 87\% answered the PITS-VAS. A proportion of participants
did not answer the anchoring task (1.67\%). After winsorizing extreme
values (top and bottom 0.1\%) (\emph{{Applying Contemporary Statistical
Techniques}} 2003) and conducting multiple imputation by chained
equations on the missing values, the mean (SD) and median (IQR) PITS
utility value was 0.282 (1.456) and 0.5 (0.6). The distribution of WAItE
PITS utility values (after winsorizing and imputation) is presented in
Figure~\ref{fig-hist}.

\begin{figure}

\centering{

\includegraphics{hesg_paper_files/figure-pdf/fig-hist-1.pdf}

}

\caption{\label{fig-hist}Distribution of PITS utility values}

\end{figure}%

\subsection{Social utility function
estimation}\label{social-utility-function-estimation}

Personal utility functions were estimated individually for each
participant in our analysis sample via methods outlined in
Section~\ref{sec-OPUF_methods}. After this, individual PUFs were
aggregated into a group utility function and anchored using the group
PITS utility value (0.282) to give the social utility function.
Descriptive statistics from the social utility function are presented in
Table~\ref{tbl-suf} whereby the mean values can be used to estimate
utility values for WAItE health states.

\begin{longtable}[]{@{}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.3864}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2386}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.2386}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.0682}}
  >{\raggedright\arraybackslash}p{(\columnwidth - 8\tabcolsep) * \real{0.0682}}@{}}

\caption{\label{tbl-suf}Social utility function based on 300 PUFs}

\tabularnewline

\toprule\noalign{}
\begin{minipage}[b]{\linewidth}\raggedright
Dimension Level
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Mean (95\% CI)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Median (Q1; Q3)
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Min
\end{minipage} & \begin{minipage}[b]{\linewidth}\raggedright
Max
\end{minipage} \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
tired, almost never & 0.029 (0.025; 0.033) & 0.029 (0.027; 0.03) & 0.021
& 0.039 \\
tired, sometimes & 0.052 (0.048; 0.057) & 0.052 (0.05; 0.054) & 0.042 &
0.062 \\
tired, often & 0.088 (0.082; 0.094) & 0.088 (0.085; 0.09) & 0.077 &
0.103 \\
tired, always & 0.14 (0.133; 0.148) & 0.14 (0.137; 0.143) & 0.125 &
0.157 \\
walk, almost never & 0.021 (0.018; 0.024) & 0.021 (0.02; 0.022) & 0.016
& 0.027 \\
walk, sometimes & 0.045 (0.041; 0.049) & 0.045 (0.043; 0.046) & 0.037 &
0.052 \\
walk, often & 0.075 (0.069; 0.082) & 0.075 (0.073; 0.077) & 0.064 &
0.087 \\
walk, always & 0.116 (0.108; 0.124) & 0.115 (0.113; 0.118) & 0.101 &
0.131 \\
sports, almost never & 0.012 (0.01; 0.015) & 0.012 (0.012; 0.013) &
0.009 & 0.017 \\
sports, sometimes & 0.023 (0.02; 0.025) & 0.023 (0.022; 0.024) & 0.018 &
0.029 \\
sports, often & 0.038 (0.034; 0.044) & 0.038 (0.037; 0.04) & 0.029 &
0.052 \\
sports, always & 0.069 (0.063; 0.076) & 0.069 (0.067; 0.071) & 0.058 &
0.084 \\
concentrate, almost never & 0.026 (0.023; 0.03) & 0.026 (0.025; 0.028) &
0.019 & 0.034 \\
concentrate, sometimes & 0.051 (0.047; 0.055) & 0.051 (0.049; 0.052) &
0.044 & 0.06 \\
concentrate, often & 0.08 (0.074; 0.086) & 0.08 (0.078; 0.082) & 0.069 &
0.093 \\
concentrate, always & 0.121 (0.114; 0.128) & 0.121 (0.118; 0.123) &
0.107 & 0.138 \\
embarrassment, almost never & 0.012 (0.01; 0.014) & 0.012 (0.011; 0.013)
& 0.008 & 0.017 \\
embarrassment, sometimes & 0.022 (0.019; 0.025) & 0.022 (0.021; 0.023) &
0.016 & 0.027 \\
embarrassment, often & 0.034 (0.03; 0.038) & 0.034 (0.032; 0.035) &
0.025 & 0.043 \\
embarrassment, always & 0.061 (0.056; 0.067) & 0.061 (0.059; 0.063) &
0.051 & 0.072 \\
unhappiness, almost never & 0.025 (0.022; 0.029) & 0.025 (0.024; 0.026)
& 0.019 & 0.033 \\
unhappiness, sometimes & 0.054 (0.049; 0.059) & 0.054 (0.052; 0.056) &
0.045 & 0.064 \\
unhappiness, often & 0.083 (0.076; 0.09) & 0.083 (0.081; 0.086) & 0.07 &
0.101 \\
unhappiness, always & 0.124 (0.117; 0.133) & 0.124 (0.122; 0.127) & 0.11
& 0.142 \\
treated differently, almost never & 0.019 (0.016; 0.022) & 0.019 (0.017;
0.02) & 0.013 & 0.025 \\
treated differently, sometimes & 0.035 (0.03; 0.039) & 0.035 (0.033;
0.036) & 0.026 & 0.043 \\
treated differently, often & 0.052 (0.047; 0.058) & 0.052 (0.05; 0.054)
& 0.041 & 0.063 \\
treated differently, always & 0.087 (0.079; 0.095) & 0.087 (0.084;
0.089) & 0.071 & 0.101 \\

\end{longtable}

Figure~\ref{fig-sufplain} presents the mean social utility function
(thick line) alongside individual personal utility functions (thin
lines) for a selection of 100 WAItE health states ordered from high to
low utility according to the social preference. Deviations of individual
utility functions from the social preference illustrate the
heterogeneity of preference within our analysis sample. Individual
personal utility functions shown in Figure~\ref{fig-sufplain} are
anchored using individual PITS utility values rather than the social
PITS utility value.

\begin{figure}

\centering{

\includegraphics{hesg_paper_files/figure-pdf/fig-sufplain-1.pdf}

}

\caption{\label{fig-sufplain}Social and individual utility functions}

\end{figure}%

\subsection{Preference heterogeneity}\label{preference-heterogeneity-1}

After estimating individual PUFs for all participants, pairwise EUD was
estimated between all participants. This yielded a {[}300 (\times)
300{]} distance matrix with 44,850 unique pairwise comparisons. The mean
(SD) and median (IQR) EUD were 47.60 (19.40) and 44.81 (34.06; 57.40).
The highest and lowest observed EUD were 189.16 and 0.
Figure~\ref{fig-eud} illustrates the relationship between EUD and WAItE
health states. EUD tends to increase as WAItE health states worsen. That
is, as the severity of WAItE health states increases, the more
heterogeneous preferences become among our sample.

\begin{figure}

\centering{

\includegraphics{hesg_paper_files/figure-pdf/fig-eud-1.pdf}

}

\caption{\label{fig-eud}Social and individual utility functions coloured
by EUD}

\end{figure}%

\subsection{PERMANOVA}

Table~\ref{tbl-permanova} presents the PERMANOVA model results.
Presented are within‐group sum‐of‐squares (SS(\_W)) for each group
individually and for all groups combined, and the corresponding
R(\^{}2), pseudo (F), and (p) values. Preference heterogeneity was
significantly affected by age ((p) = 0.03), though the amount of
variability in preferences that could be explained by age was relatively
small (R(\^{}2)=5.7\%). Figure~\ref{fig-age} presents the difference in
preferences between different age groups. Generally, as age increases,
health state utility values for each given WAItE health state are
higher. That is, younger populations tend to place more disutility on
WAItE health problems than older populations. While weight status was
not significantly related to preference heterogeneity according to the
PERMANOVA model, given the WAItE is a weight-specific measure, it was
informative to explore the relationship between preferences and weight
status. Though not statistically significant, we can observe a
difference in preferences between normal weight and overweight
individuals in Figure~\ref{fig-weight}. For a given WAItE health state,
overweight individuals in our sample placed less disutility on that
state than did normal weight individuals.

\begin{longtable}[]{@{}lrrrrr@{}}

\caption{\label{tbl-permanova}Results of PERMANOVA -- testing for
differences in WAItE health state preferences between group
characteristics}

\tabularnewline

\toprule\noalign{}
& Df & SumOfSqs & R2 & F & Pr(\textgreater F) \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
age\_factor & 6 & 8103.932 & 0.040 & 2.012 & 0.001 \\
weightdata & 4 & 2957.825 & 0.014 & 1.102 & 0.321 \\
educationdata & 5 & 4307.037 & 0.021 & 1.283 & 0.136 \\
occupationdata & 7 & 4180.638 & 0.020 & 0.890 & 0.659 \\
genderdata & 3 & 723.163 & 0.004 & 0.359 & 0.986 \\
ethnicitydata & 4 & 2963.218 & 0.014 & 1.104 & 0.312 \\
Residual & 270 & 181227.225 & 0.886 & NA & NA \\
Total & 299 & 204463.039 & 1.000 & NA & NA \\

\end{longtable}

\begin{figure}

\centering{

\includegraphics{hesg_paper_files/figure-pdf/fig-age-1.pdf}

}

\caption{\label{fig-age}Social and individual utility functions grouped
by age status}

\end{figure}%

\subsection{Sensitivity analysis}\label{sensitivity-analysis-1}

EUD2 was estimated for each pairwise comparison of individuals in our
study. This yielded a {[}300 (\times) 300{]} distance matrix with 44,850
unique pairwise comparisons. The mean (SD) and median (IQR) EUD were
34.30 (13.82) and 32.25 (24.54; 41.27). Results from the PERMANOVA2
analysis are presented in Table~\ref{tbl-permanova2}. After exclusion of
individual variation in anchoring responses, weight status and age had a
significant impact upon heterogeneity within our sample; though the
amount of heterogeneity that was explained by these variables was fairly
small (4.9\%).

\begin{longtable}[]{@{}lrrrrr@{}}

\caption{\label{tbl-permanova2}Results of PERMANOVA2 -- testing for
differences in level rating and domain weighting preferences between
group characteristics}

\tabularnewline

\toprule\noalign{}
& Df & SumOfSqs & R2 & F & Pr(\textgreater F) \\
\midrule\noalign{}
\endhead
\bottomrule\noalign{}
\endlastfoot
age\_factor & 6 & 8103.932 & 0.040 & 2.012 & 0.001 \\
weightdata & 4 & 2957.825 & 0.014 & 1.102 & 0.321 \\
educationdata & 5 & 4307.037 & 0.021 & 1.283 & 0.136 \\
occupationdata & 7 & 4180.638 & 0.020 & 0.890 & 0.659 \\
genderdata & 3 & 723.163 & 0.004 & 0.359 & 0.986 \\
ethnicitydata & 4 & 2963.218 & 0.014 & 1.104 & 0.312 \\
Residual & 270 & 181227.225 & 0.886 & NA & NA \\
Total & 299 & 204463.039 & 1.000 & NA & NA \\

\end{longtable}

\section{Discussion}\label{discussion}

This study is the first time that the OPUF has been used to estimate
health state utility values for the WAItE. We obtained a representative
sample of high quality data from Prolific, a survey company known for
their high quality respondents (Peer et al. 2022). Our average domain
weightings and implied ordering were similar to those exhibited in
Robinson et al.~(XX VIH).

Anchoring of the WAItE PITS state was a difficult procedure that
required a number of methodological decisions. We decided to use
uncensored responses to the Dead-VAS task which meant that data from one
respondent (-99) skewed the mean PITS utility value quite substantially.
To mitigate the impact of extreme values on the mean, we conducted
winsorization of values lying in the outer 0.1\% of the distribution.
This practice, while effective at limiting the influence of extreme
values on the mean, could understate the genuine variability in the
data. Though, it is likely that exclusion of this participant would have
had a more detrimental effect to presenting the genuine variability of
responses.

The social utility function elicited through this study, and underlying
utility value set, present monotonic preferences which behave as we
would have expected ex-ante (based on qualitative piloting work).
Tiredness and Unhappiness were considered the most important domains
while Embarrassment and Sports the least. This finding concurs with
qualitative work conducted prior and also is in accordance with previous
valuation work done with the WAItE (XX VIH). Prior valuation work, which
used a DCE to elicit preferences, yielded latent coefficients which
violated the rational choice axiom of monotonicity. In the OPUF,
monotonicity is somewhat forced through the choice architecture of the
level rating and through the additional prompt to reconsider responses
that are not monotonic. Forced monotonicity, in this context, could be
problematic for eliciting unbiased preferences if preferences for
certain health states are truly not monotonic. For example, prior
qualitative work has suggested that ``I almost never get tired'' might
be preferable to ``I never get tired'' in some circumstances where
respondents are thinking about experiencing insomnia and sleep quality.
This being said, the WAItE descriptive system was designed to be a
monotonic descriptive system, validated using Rasch analysis, and so
having a monotonic utility value set makes logical sense.

Preferences elicited through this study were considerably heterogeneous.
This can be understood through the mean EUD value (47.6) but also
illustrated in Figure~\ref{fig-sufplain} through the deviations of
individual PUFs from the social utility function. Following on from
prior work (P. Schneider et al. 2024), we estimated EUD by calculating a
distance matrix between each pairwise comparison of individual value
sets for all 78125 WAItE health states. The implication of estimating
distance (preference heterogeneity) by using individual value sets
allows for much of the preference heterogeneity that exists to be
composed of differences in individual anchoring values (PITS state
responses) rather than differences in level ratings and domain
weightings. This methodological decision, ultimately, results in the
majority of EUD being composed of differences in anchoring values and
this finding is important to acknowledge. Anchoring differences are
important to present and explore, though in this preference
heterogeneity analysis could be drowning out the heterogeneity in level
ratings and domain weighting. An example of this can be shown through
the age preference heterogeneity in Figure~\ref{fig-age}. Preference
heterogeneity is evident between individuals above and below age 35 and
if we consider the mean PITS values for those two subgroups (age
(\textless) 35 = -0.281; age (\textgreater) 34 = 0.487) we can see that
a clear difference in anchoring responses is evident.

A methodological exploration was conducted as a sensitivity analysis to
limit the influence that anchoring variation has on the overall
preference heterogeneity. We considered this to be a strength of the
research as it offers a new approach to decompose preference
heterogeneity into anchoring variation and the difference in level
ratings and domain weightings. After exclusion of individual variation
in anchoring responses, weight status and age were found to have a
significant impact on preference heterogeneity within our sample; though
the amount of variation that could be explained was limited. Preference
heterogeneity between those of normal weight and those who were
overweight is illustrated in Figure Figure~\ref{fig-weight}.

\begin{figure}

\centering{

\includegraphics{hesg_paper_files/figure-pdf/fig-weight-1.pdf}

}

\caption{\label{fig-weight}Social and individual utility functions
grouped by weight status}

\end{figure}%

This method of estimating preference heterogeneity should not be
considered the gold standard, as only part of the variation in
preferences is explored here. It can however be considered an additional
option for future researchers that wish to isolate the effect of
anchoring responses on overall preference heterogeneity. It is also, to
our knowledge, the first time preference heterogeneity has been
decomposed in this way with the OPUF.

The value set estimated here offers an alternative choice of preference
values to the existing value sets estimated using DCE (shown in Figure
\ref{tab:WAITE val sets}). When comparing the anchored coefficients
between value sets, one of the key areas of divergence is where levels
have been collapsed in the DCE value set. In the OPUF, ``I almost never
get tired'' is given 0.029 compared to 0.064 in the DCE due to
collapsing levels. Generally the difference between coefficients that
have not been `collapsed' between the value sets is small suggesting
that there is comparability to an extent between the value sets.
Anchoring values were broadly similar between studies too. The mean PITS
utility values between studies were broadly comparable with a maximum
range of 0.059. Interestingly, the EQ-VAS anchoring task mean (0.289)
was remarkably similar to the OPUF VAS anchoring task mean (0.282) again
supporting the use of VAS for elicitation of PITS utility values.

\section*{Bibliography}\label{bibliography}
\addcontentsline{toc}{section}{Bibliography}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-Anderson2017}
Anderson, Marti J. 2017.{``{Permutational Multivariate Analysis of
Variance ( PERMANOVA ) }.''} In \emph{Wiley StatsRef: Statistics
Reference Online}.
\url{https://doi.org/10.1002/9781118445112.stat07841}.

\bibitem[\citeproctext]{ref-2003ApplyingTechniques}
\emph{{Applying Contemporary Statistical Techniques}}. 2003.
\url{https://doi.org/10.1016/b978-0-12-751541-0.x5021-4}.

\bibitem[\citeproctext]{ref-BanaECosta1999TheApplication}
Bana E Costa, Carlos A., and Jean-Claude Vansnick. 1999. {``{The MACBETH
Approach: Basic Ideas, Software, and an Application}.''} In.
\url{https://doi.org/10.1007/978-94-017-0647-6\%7B/_\%7D9}.

\bibitem[\citeproctext]{ref-Belton2002MultipleAnalysis}
Belton, Valerie, and Theodor J. Stewart. 2002. \emph{{Multiple Criteria
Decision Analysis}}. Springer US.
\url{https://doi.org/10.1007/978-1-4615-1495-4}.

\bibitem[\citeproctext]{ref-Bray2024DevelopmentImpairment}
Bray, Nathan, Rhiannon Tudor Edwards, and Paul Schneider. 2024.
{``{Development of a value-based scoring system for the MobQoL-7D: a
novel tool for measuring quality-adjusted life years in the context of
mobility impairment}.''} \emph{Disability and Rehabilitation}, 1--10.
\url{https://doi.org/10.1080/09638288.2023.2297929}.

\bibitem[\citeproctext]{ref-Brodszky2023PCR108States}
Brodszky, V., S. Plankó, P. Schneider, and N. Devlin. 2023. {``{PCR108
Pilot Testing the Hungarian Version of Online Elicitation of Personal
Utility Functions Tool for Valuing EQ-5D-5L Health States}.''}
\emph{Value in Health} 26 (12): S469.
\url{https://doi.org/10.1016/j.jval.2023.09.2547}.

\bibitem[\citeproctext]{ref-Danner2011IntegratingPreferences}
Danner, Marion, J. Marjan Hummel, Fabian Volz, Jeannette G. Van Manen,
Beate Wiegard, Charalabos Markos Dintsios, Hilda Bastian, Andreas
Gerber, and Maarten J. Ijzerman. 2011. {``{Integrating patients' views
into health technology assessment: Analytic hierarchy process (AHP) as a
method to elicit patient preferences}.''} \emph{International Journal of
Technology Assessment in Health Care} 27 (4).
\url{https://doi.org/10.1017/S0266462311000523}.

\bibitem[\citeproctext]{ref-Devlin2019AFunctions}
Devlin, Nancy J., Koonal K. Shah, Brendan J. Mulhern, Krystallia
Pantiri, and Ben van Hout. 2019. {``{A new method for valuing health:
directly eliciting personal utility functions}.''} \emph{European
Journal of Health Economics} 20 (2).
\url{https://doi.org/10.1007/s10198-018-0993-z}.

\bibitem[\citeproctext]{ref-Hauber2016StatisticalForce}
Hauber, A. Brett, Juan Marcos González, Catharina G. M.
Groothuis-Oudshoorn, Thomas Prior, Deborah A. Marshall, Charles
Cunningham, Maarten J. IJzerman, and John F. P. Bridges. 2016.
{``{Statistical Methods for the Analysis of Discrete Choice Experiments:
A Report of the ISPOR Conjoint Analysis Good Research Practices Task
Force}.''} \emph{Value in Health} 19 (4).
\url{https://doi.org/10.1016/j.jval.2016.04.004}.

\bibitem[\citeproctext]{ref-Keeney1979DecisionsTrade-Offs}
Keeney, R. L., and H. Raiffa. 1979. {``{Decisions with Multiple
Objectives: Preferences and Value Trade-Offs}.''}
\url{https://doi.org/10.1109/TSMC.1979.4310245}.

\bibitem[\citeproctext]{ref-Marsh2016MultipleForce}
Marsh, Kevin, Maarten Ijzerman, Praveen Thokala, Rob Baltussen, Meindert
Boysen, Zoltán Kaló, Thomas Lönngren, et al. 2016. {``{Multiple Criteria
Decision Analysis for Health Care Decision Making - Emerging Good
Practices: Report 2 of the ISPOR MCDA Emerging Good Practices Task
Force}.''} \emph{Value in Health} 19 (2).
\url{https://doi.org/10.1016/j.jval.2015.12.016}.

\bibitem[\citeproctext]{ref-Oliveira2018ValuingStates}
Oliveira, Mónica Duarte, Andreia Agostinho, Lara Ferreira, Paulo Nicola,
and Carlos Bana E Costa. 2018. {``{Valuing health states: Is the MACBETH
approach useful for valuing EQ-5D-3L health states?}''} \emph{Health and
Quality of Life Outcomes} 16 (1).
\url{https://doi.org/10.1186/s12955-018-1056-y}.

\bibitem[\citeproctext]{ref-Peer2022DataResearch}
Peer, Eyal, David Rothschild, Andrew Gordon, Zak Evernden, and Ekaterina
Damer. 2022. {``{Data quality of platforms and panels for online
behavioral research}.''} \emph{Behavior Research Methods} 54 (4).
\url{https://doi.org/10.3758/s13428-021-01694-3}.

\bibitem[\citeproctext]{ref-Robinson2019EstimatingEvaluation}
Robinson, Tomos, and Yemi Oluboyede. 2019. {``{Estimating CHU-9D Utility
Scores from the WAItE: A Mapping Algorithm for Economic Evaluation}.''}
\emph{Value in Health} 22 (2).
\url{https://doi.org/10.1016/j.jval.2018.09.2839}.

\bibitem[\citeproctext]{ref-Schneider2022TheStates}
Schneider, P P, B van Hout, M Heisen, J Brazier, and N Devlin. 2022.
{``{The Online Elicitation of Personal Utility Functions (OPUF) tool: a
new method for valuing health states}.''} \emph{Wellcome Open Res} 7:
14. \url{https://doi.org/10.12688/wellcomeopenres.17518.1}.

\bibitem[\citeproctext]{ref-Schneider2024ExploringLevel}
Schneider, Paul, Nancy Devlin, Ben van Hout, and John Brazier. 2024.
{``{Exploring health preference heterogeneity in the UK: Using the
online elicitation of personal utility functions approach to construct
EQ-5D-5L value functions on societal, group and individual level}.''}
\emph{Health Economics (United Kingdom)} 33 (5).
\url{https://doi.org/10.1002/hec.4805}.

\bibitem[\citeproctext]{ref-Souza2013PopulationEstuary}
Souza, Allan T., Ester Dias, Ana Nogueira, Joana Campos, João C.
Marques, and Irene Martins. 2013. {``{Population ecology and habitat
preferences of juvenile flounder Platichthys flesus (Actinopterygii:
Pleuronectidae) in a temperate estuary}.''} \emph{Journal of Sea
Research} 79. \url{https://doi.org/10.1016/j.seares.2013.01.005}.

\bibitem[\citeproctext]{ref-White2011MultiplePractice}
White, Ian R., Patrick Royston, and Angela M. Wood. 2011. {``{Multiple
imputation using chained equations: Issues and guidance for
practice}.''} \emph{Statistics in Medicine} 30 (4).
\url{https://doi.org/10.1002/sim.4067}.

\end{CSLReferences}




\end{document}
